### ISSUE TITLE
Flash issues

### ISSUE THREAD

**Issue by jmodrako** [dronecz/maker_badge#3]
Hey! I wanted to flash CircuitPython to the board but I've failed.

WINDOWS: I've holded BOOT button while plugging USB C cable. In device manager I can see COM port for it, but there is also a Other devices section with ESP32-S2 entry.  But on the other hand in Thonny I was able to put .bin file and flash correctly, but after a reset nothing happen, it can't start.

Can you help me somehow? Do I need some special windows drivers to get it working?

**Comment by cqeta1564** [comment]
Hi, 
I use this internet browser flasher and it works great, here is a link to the page: [https://nabucasa.github.io/esp-web-flasher/](https://nabucasa.github.io/esp-web-flasher/). I personally use it in google chrome, which works the best for me. You just plug in the board and don't forget to hold BOOT button than connect it. Add .bin file to the first line and PROGRAM without any offset. 
![adafruit_products_Screen_Shot_2022-04-04_at_3 18 26_PM](https://user-images.githubusercontent.com/115307180/223524666-c3329db4-a733-461b-8f7e-7d06cc0f75fe.png)

**Comment by jmodrako** [comment]
Man!!! I owe you a big big very big beeer! I was able to flash it via this web site and then put proper firmware through Thonny ;)

Thanks again!
