### ISSUE TITLE
e-paper display not working

### ISSUE THREAD

**Issue by jmodrako** [dronecz/maker_badge#4]
I've downloaded an example for CircuitPython nad it seems that LEDs are working great but the e-ink is not refreshing at all. 

But, when I've checked Arduino INO test, then display works corretly.

Any ideas? :)

**Comment by cqeta1564** [comment]
Hi, have you tried CyrcuitPython/main.py example? ([Link here](https://github.com/dronecz/maker_badge/blob/main/SW/CircuitPython/examples/MF%20basic%20rev.B/code.py)) I think that one should work. If not than i would definitly check hardware, like if the connector is pluged in correctly. Sorry for my bad english, it’s not my main language :)

**Comment by jmodrako** [comment]
No worries, I'm not an english man too :) 

Regarding the code, I did a try and it hangs on `display.refresh()`:

<img width="532" alt="image" src="https://user-images.githubusercontent.com/4301302/224177560-464b265f-6341-4221-a8d4-6fe1019bf055.png">

But as I said, the Arduino example works, and the display shows the content without any issues.

**Comment by dronecz** [comment]
Hello Jacek, 

if I remember correctly, you own rev.A of the board which has e-ink with lower resolution. 

I just [uploaded ](https://github.com/dronecz/maker_badge/tree/main/SW/CircuitPython/examples/MF%20basic%20rev.A)example for rev.A so please test it. It works on my device so I hope it will solve your issue. 

Sorry that I did not make it earlier and you had to deal with this. 😞 

If this helped, please close the issue 🙂.

Thanks

**Comment by jmodrako** [comment]
Ok, so now there is something going on on the display but with issues.

But I must confess that I've replaced the original display because the previous one I've broken (don't ask how...). But I did buy the same model (I've checked the code that has been placed on the connector, please see on the photo).

This model I bought: https://download.kamami.pl/p582532-2.13inch_e-Paper_%28D%29_Datasheet.pdf

https://kamami.pl/wyswietlacze-e-paper/582532-213inch-e-paper-d-elastyczny-wyswietlacz-e-paper-213-212x104.html

And the photos:

<img width="536" alt="image" src="https://user-images.githubusercontent.com/4301302/224180989-530e8992-710d-4487-81b2-2df9058915f8.png">

The new display code (the same as the original one, but the new one is flexible):
<img width="396" alt="image" src="https://user-images.githubusercontent.com/4301302/224181021-f7a04813-8883-4240-ac39-93b46dc845be.png">

**Comment by jmodrako** [comment]
I've found out the chip that is responsible for that display: 

`GDEW0213Z16 2.13" b/w/r 104x212, UC8151 (IL0373)`

And it seems that we already have proper library `adafruit_uc8151d`.

**Comment by dronecz** [comment]
I think that you have to use [this ](https://github.com/adafruit/Adafruit_CircuitPython_IL0373/releases/tag/1.3.17) driver. 

Download `.mpy` file for 8.x CPY, unzip it and place it in to the lib folder at CIRCUITPY drive.  I would they try to change `import adafruit_uc8151d` to `adafruit_il0373` and `display = adafruit_uc8151d.UC8151D` to `display = adafruit_il0373.IL037`. 

Everything else should remain same. 

Let me know if that helped.

**Comment by jmodrako** [comment]
I've had this code:

```python
import time
import terminalio
import board
import neopixel
import touchio
import displayio
import adafruit_il0373
# GDEW0213Z16 2.13" b/w/r 104x212, UC8151 (IL0373)
from adafruit_display_text import label

# Function for append text to the display data
def _addText(text, scale, color, x_cord, y_cord):
    group = displayio.Group(scale = scale, x = x_cord, y = y_cord)
    text_label = label.Label(terminalio.FONT, text = text, color = color)
    group.append(text_label)
    display_data.append(group)

# Define board pinout
board_spi = board.SPI()  # Uses SCK and MOSI
board_epd_cs = board.D41
board_epd_dc = board.D40
board_epd_reset = board.D39
board_epd_busy = board.D42

# Define touch buttons
touch_threshold = 20000
touch_1 = touchio.TouchIn(board.D5)
touch_1.threshold = touch_threshold
touch_2 = touchio.TouchIn(board.D4)
touch_2.threshold = touch_threshold
touch_3 = touchio.TouchIn(board.D3)
touch_3.threshold = touch_threshold
touch_4 = touchio.TouchIn(board.D2)
touch_4.threshold = touch_threshold
touch_5 = touchio.TouchIn(board.D1)
touch_5.threshold = touch_threshold

# Define LED
led_pin = board.D18
led_matrix = neopixel.NeoPixel(led_pin, 4, brightness = 0.1, auto_write = False)

# Define LED colors value
led_off = (0, 0, 0)
led_red = (255, 0, 0)
led_green = (0, 255, 0)
led_blue = (0, 0, 255)

# Define ePaper display colors value
display_black = 0x000000
display_white = 0xFFFFFF

# Define ePaper display resolution
display_width = 212
display_height = 104

# Prepare ePaper display
displayio.release_displays()
display_bus = displayio.FourWire(
    board_spi, command = board_epd_dc, chip_select = board_epd_cs, reset = board_epd_reset, baudrate = 1000000
)
time.sleep(1)
display = adafruit_il0373.IL0373(
    display_bus, width = display_width, height = display_height, rotation = 90, busy_pin = board_epd_busy, swap_rams=True
)
display_data = displayio.Group()
display_background = displayio.Bitmap(display_width, display_height, 1)
display_color_palette = displayio.Palette(1)
display_color_palette[0] = display_white

# Append tilegrid with the background to the display data
display_data.append(displayio.TileGrid(display_background, pixel_shader = display_color_palette))

# Render namecard to display
_addText("Name", 3, display_black, 70, 20)
_addText("Surname", 3, display_black, 45, 55)
_addText("Company/Project", 2, display_black, 20, 90)

print("1")
display.show(display_data)
print("2")
display.refresh()
print("3")

# MAIN LOOP
while True:
    if touch_1.value:
        # Turn off the LED
        led_matrix.fill(led_off)
        led_matrix.show()
    if touch_2.value:
        # Set LED to red
        led_matrix.fill(led_red)
        led_matrix.show()
    if touch_3.value:
        # Set LED to green
        led_matrix.fill(led_green)
        led_matrix.show()
    if touch_4.value:
        # Set LED to blue
        led_matrix.fill(led_blue)
        led_matrix.show()
    if touch_5.value:
        # Turn off the LED
        led_matrix.fill(led_off)
        led_matrix.show()
```

And the `refresh` is not blocking, but on the display nothing really happens, compared to the version with `ssd1680` where actually something have happened, but in completely random way.

**Comment by jmodrako** [comment]
OK! Code with `adafruit_il0373.IL0373` works! It looks like it was some loose connection. I've made some movement and it started working 👯 So I'm closing this issue. Thanks for the help guys!
